apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: cody-demo
  labels:
    app: bootcamp
spec:
  selector:
    matchLabels:
      app: bootcamp
      role: db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: bootcamp
        role: db
        tier: backend
    spec:
      containers:
      - name: db
        image: harbor.humblelab.com/library/cmbu-db-app:latest
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapi
  namespace: cody-demo
  labels:
    app: bootcamp
spec:
  selector:
    matchLabels:
      app: bootcamp
      role: api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: bootcamp
        role: api
        tier: backend
    spec:
      containers:
      - name: pyapi
        image: harbor.humblelab.com/library/cmbu-app-backend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmbu-app-frontend
  namespace: cody-demo
  labels:
    app: bootcamp
spec:
  selector:
    matchLabels:
      app: bootcamp
      role: web
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: bootcamp
        role: web
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: harbor.humblelab.com/library/cmbu-app-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pyapi
  namespace: cody-demo
  labels:
    app: bootcamp
    role: api
    tier: backend
spec:
  ports:
  - port: 80
  selector:
    app: bootcamp
    role: api
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cody-demo
  labels:
    app: bootcamp
    role: db
    tier: backend
spec:
  ports:
  - port: 5432
  selector:
    app: bootcamp
    role: db
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: cody-demo
  labels:
    app: bootcamp
    role: web
    tier: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp
    role: web
    tier: frontend
  type: LoadBalancer
